### ISSUE TITLE
Inserting much data in 1 tx causing OOM Killer

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#259] opened 2022-01-10 06:19 UTC
Branch: gc-254
Server has 64Gb RAM
Inserting much data in 1 tx causing OOM Killer.
Heap of application is 110Mb (means no leak of memory allocated by go's runtime)
Pseudocode: 
```
v := new([]byte, 100*1024*1024) // 100Mb
k := new([]byte, 8)

tx := db.Begin()
for i := uint64(0); i < 10_000; i++ {
	binary.BigEndian.PutUint64(k, i)
	tx.Put(dbi, k, v)
}
tx.Commit()
```

**Comment by erthink** [comment] 2022-01-10 09:53
This is effect of https://github.com/erthink/libmdbx/issues/192:
- I.e. historically (and now) libmdbx to going spilling (to spill a dirty-pages from memory to a disk) counts only a number of entries of dirty-page list, but not the number of pages.
- This is not a problem until you puts a lot of large new values which are requires the large/overflow pages.
- Otherwise the dirty-page list will be short (and will not trigger pages spilling) but many the large entries with overflowed-pages, which may lead to OOM.

**Comment by erthink** [comment] 2022-01-10 09:55
Inherently this is duplicate of https://github.com/erthink/libmdbx/issues/192.

**Closed by erthink** 2022-01-10 09:55 UTC
Labels: duplicate

**Comment by AskAlexSharov** [comment] 2022-01-10 10:04
Good
