### ISSUE TITLE
MSVC's bug: Building with Visual studio 2019 stuck

### ISSUE THREAD

**Issue by gogolxdong** [erthink/libmdbx#154] opened 2021-01-19 03:18 UTC
Building with Visual studio 2019 after cmake . stuck at some point.

**Comment by erthink** [comment] 2021-01-19 04:21
This is MSVC compiler bug, for more info see the https://github.com/erthink/libmdbx/issues/116.

**Comment by erthink** [comment] 2021-01-20 16:54
Reopen only to stay in the wontfix state and avoid duplicates due to MSVC bugs.

**Comment by MrSmith33** [comment] 2021-03-26 23:20
When building mdbx myself, I used `Release` build with `/Ob1` switch instead of `/Ob2`.

**Comment by erthink** [comment] 2021-03-26 23:55
> When building mdbx myself, I used `Release` build with `/Ob1` switch instead of `/Ob2`.

Yes, this is [known solution](https://github.com/erthink/libmdbx/issues/116#issuecomment-691735471).

**Comment by erthink** [comment] 2021-07-26 13:11
Seems M$ fixed this issue silently, at least it don't reproduced on the Visual Studio 2019 release 16.10.

**Closed by erthink** 2021-07-26 13:11 UTC
Labels: duplicate, not-a-bug, wontfix
