### ISSUE TITLE
MDBX_PAGE_NOTFOUND - after switch from devel to master

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#187] opened 2021-04-26 08:12 UTC
Last change I did: switched mdbx version from devel to master. 
from #define MDBX_BUILD_SOURCERY 8d84a8c94bf33a8a4b959516546f5a33458865e5e2d0f744710c43cf76e37cbd_v0_9_3_125_g2c717590
to 
#define MDBX_BUILD_SOURCERY 046df7b80c64f3c3baece47f5dad4454d143536b299685cc71d69ecd83016d5b_v0_9_3_104_g934ca25a

Debug logs: 
```
mdbx_setup_dxb:14452 open-MADV_DONTNEED 19373708..19398656
mdbx_set_readahead:8471 readahead OFF 0..19373708
badpage: corrupted leaf-page #193, mod-txnid 73433
badpage: page mod-txnid (73433) > parent (73432)
mdbx_put: MDBX_PAGE_NOTFOUND: Requested page not found
```

./build/bin/mdbx_chk 
```

Iterating DBIs...
 ! corrupted leaf-page #193, mod-txnid 73433
 ! page mod-txnid (73433) > parent (73432)
 ! mdbx_cursor_get failed, error -30797 MDBX_PAGE_NOTFOUND: Requested page not found
 - problems: different number of entries (1)
Total 4 errors are detected, elapsed 1589.541 seconds.
```

**Comment by erthink** [comment] 2021-04-26 08:23
This is the temporary regression in the `master` branch which visible in a huge (i.e. your) use cases, and will be "automatically fixed' by merge the `devel` into the `master` soon.

Thanks for reporting.

**Comment by AskAlexSharov** [comment] 2021-04-26 08:38
Ok. After switch to current devel: `mdbx_put: operation not permitted`

**Comment by erthink** [comment] 2021-04-26 09:26
Do I understand correctly that this is the same problem as in https://github.com/erthink/libmdbx/issues/188 ?

**Comment by AskAlexSharov** [comment] 2021-04-26 10:29
Yes, just discovered independently

**Comment by erthink** [comment] 2021-04-26 10:46
Understood. So, I close this issue as a duplicate of #188, since there is more information and a more relevant title.

**Closed by erthink** 2021-04-26 10:46 UTC
