### ISSUE TITLE
Crash on APPENDDUP

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#126] opened 2020-10-23 07:35 UTC
[backtrace.log](https://github.com/erthink/libmdbx/files/5427953/backtrace.log)
Oops, it's with `-O2`, will create one with `-O0` in 2-3 hours.

**Comment by erthink** [comment] 2020-10-23 09:38
> [backtrace.log](https://github.com/erthink/libmdbx/files/5427953/backtrace.log)
> Oops, it's with `-O2`, will create one with `-O0` in 2-3 hours.

`-Og` is enough in most cases but runs much faster.

Nonetheless, current backtrace is enough.
More precisely, it is already clear that backtrace will not help, since the problem happened earlier, i.e. I need to look for a way to reproduce bug through simple tests.

**Comment by erthink** [comment] 2020-10-23 09:58
Hypothetically, we can try enabling internal audit.
But in your scenarios (and volumes), it may take weeks for the test to reach the bug.

If you have a persistent dataset and a reproducible sequence of operations, we can use an audit-enabled build, but turn audit on immediately before the transaction in which error occurs.

However, it is desirable for me to have a lean testcase based on the current "test framework" to include it in CI.
So I will try to reproduce the problem (i.e. find a testcase) at least today and over the weekend.

**Comment by AskAlexSharov** [comment] 2020-10-23 15:26
mdbx_chk didn't find errors that db. loading of very similar (but not totally same) data to empty db - passed successfully. will collect full dataset tonight, then will try to reduce it.

**Comment by erthink** [comment] 2020-10-23 15:32
> mdbx_chk didn't find errors that db. loading of very similar (but not totally same) data to empty db - passed successfully. will collect full dataset tonight, then will try to reduce it.

This is the expected behavior because an erroneous transaction was not committed (cannot be committed).

**Comment by AskAlexSharov** [comment] 2020-10-24 01:39
here data set 14Gb (42Gb): http://188.166.233.190/alex_full.log.gz
smaller data sets don't reproduce problem

**Comment by AskAlexSharov** [comment] 2020-10-24 06:32
FYI: Something more broken in last devel (just did git pull), 1 test in our project failed - but test is complex and i didn’t understand yet what’s wrong (it looks like cursor returned too short value - shorter than anything i put to DBI. But not 100% sure yet).

**Comment by AskAlexSharov** [comment] 2020-10-26 02:40
On today's `devel` my test passed

**Comment by erthink** [comment] 2020-10-26 14:30
I still don't know if there was a problem/error, what caused it, or if anything was fixed.
So I'll continue working with the tests and your test data.

**Comment by erthink** [comment] 2020-10-26 23:05
Некоторые методы и результаты проверок (кроме доработок и прогона mdbx_test):

1. Ваши "логи" я преобразовал в текстовый дамп BerkeleyDB, формат которого исторически используется в mdbx_dump и mdbx_load.

```
VERSION=3
geometry=l268435456,c268435456,u25769803776,s268435456,g268435456
mapsize=756375552
maxreaders=120
format=bytevalue
database=TBL0001
type=btree
db_pagesize=4096
duplicates=1
dupsort=1
HEADER=END
```
```
$ (cat HEADER && gzip -d < alex_full.log.gz | sed 's/^\([0-9a-f]\+\),\([0-9a-f]\+\)$/ \1\n \2/g' && echo DATA=END) | lz4 > src.dump.lz4
```

2. Этот дамп я загрузил в новую БД посредством `mdbx_load`.
Технически при этом используются аналогичные вашим операции добавления данных через курсор.
```
$ lz4 -d < src.dump.lz4 | ./mdbx_load -an proba.db
```

3. После этого получил её дамп, посчитал sha256-дайджест и сравнил с исходным:
```
$ ./mdbx_dump -a proba.db | tail -n +4 | sha256sum
mdbx_dump v0.9.1-60
Running for proba.db...
ac8a2c7f9acc2201a4c1fc64829aed476821dbfb4c5685e12a422939c80efb09  -
```

```
$ lz4 -d < src.dump.lz4 | tail -n +4 | sha256sum
ac8a2c7f9acc2201a4c1fc64829aed476821dbfb4c5685e12a422939c80efb09 -
```
Прослойка `tail -n +4` здесь нужна чтобы отрезать строки заголовка зависящие от размера БД, который после загрузки данных определяется самими данными.
Соответственно, при равенстве дайджестов можно надеяться на совпадение исходных данных и содержимого БД.

На всякий:
```
$ sha256sum alex_full.log.gz
	0cc400fbeda306d89c4e68aa120a2b5983624e0874578699e33914f9a4a0ae5c  alex_full.log.gz
```
---

Это для текущей ветки `devel`.
Чуть позже попробую по `git reflog` проверить предыдущие версии, чтобы понять была ли проблема и каким коммитом она исправлена.

**Comment by erthink** [comment] 2020-10-27 01:20
So, I didn't found trouble at commits: faddc71eace1088f077a022a235cd097ef0c21c2, ca2ecf2289d8d2e60016b1d349f62eff537e76b6, 2120e396fcb93190bf8b10f51780b1574b18ae2f, 112ce742f501ee31190fda1060b6356f437fcef3, etc (afa264b6, 44b1a3bc).

However, there is space for human error.
So, feed me the commit where you had problems, if there is such information.

**Comment by AskAlexSharov** [comment] 2020-10-27 05:40
Thank, very useful guide on how to get and share mdbx dumps. Only problem - i can't use mdbx_dump if APPEND_DUP returned error (because last key - where error happened - not written into db). 

Let me run again that script which failed on last devel (next time I will add commit hash into messages): faddc71eace1088f077a022a235cd097ef0c21c2

**Comment by AskAlexSharov** [comment] 2020-10-27 09:15
Reproduced on faddc71 problem with MDBX_CORRUPTED after APPEND_DUP (of that data which I sent you into DB which was not empty, but DBI was empty): 
Do I need send you full dump of db?

**Comment by erthink** [comment] 2020-10-27 13:32
> Reproduced on [faddc71](https://github.com/erthink/libmdbx/commit/faddc71eace1088f077a022a235cd097ef0c21c2) problem with MDBX_CORRUPTED after APPEND_DUP (of that data which I sent you into DB which was not empty, but DBI was empty):
> Do I need send you full dump of db?

I need a way to reproduce the problem.
So in general "yes", I would prefer to get a specific DB in its entirety (not just a dump), if this will reproduce the problem.

**Comment by erthink** [comment] 2020-10-29 00:57
Please, let us and you deal with the problem, even if it requires some effort.

**Comment by AskAlexSharov** [comment] 2020-10-29 02:32
yes, i'm working on sharing that db file... (I broken my VPN setup, re-creating it now).

**Comment by AskAlexSharov** [comment] 2020-10-30 04:37
Good news: i've succeed to reproduce problem without original DB (only on `alex_full.log`).

To do so: 
- put data only by APPENDDUP (without APPEND)
⁃ don't do intermediate commits (only 1 commit at the end, but script stops earlier).

mdbx_load - does intermediate commits and can't reproduce (when I do intermediate commits - problem also doesn't reproduce).

**Closed** 2020-10-31 00:09 UTC
Labels: bug
