### ISSUE TITLE
mdbx_load fails with MDBX_MAP_FULL: Environment mapsize limit reached

### ISSUE THREAD

**Issue by setop** [erthink/libmdbx#136] opened 2020-11-15 03:09 UTC
**Steps to reproduce the bug**

1.  `wget https://github.com/erthink/libmdbx/releases/download/v0.9.1/libmdbx-amalgamated-0.9.1.tar.gz`
1. `tar xvfz libmdbx-amalgamated-0.9.1.tar.gz`
1. `make`
1. prepare 5'000 key,value in two text files of 5'000 lines each, about 2*300KB of data ([t1.txt](https://github.com/erthink/libmdbx/files/5541780/t1.txt), [t2.txt](https://github.com/erthink/libmdbx/files/5541781/t2.txt))
1. run `./mdbx_load -T foo < t1.txt`
1. run `./mdbx_load -T foo < t2.txt`

**Expected behaviour**

first 2'500 key value pairs are loaded in the foo MDBX.
then another 2'500 key value pairs are loaded in the foo MDBX.

**Resulting behaviour**

first

```
mdbx_load v0.9.1-0-g44b1a3b (2020-09-30T13:28:01+03:00, T-cdf44eb040316fff8c20f34069d5148e758f9ab7)
Running for foo...
./mdbx_load: at input line 5000: mdbx_dbi_close() error -30780, MDBX_BAD_DBI: The specified DBI-handle is invalid or changed by another thread/transaction
```

2500 entries loaded

then

```
mdbx_load v0.9.1-0-g44b1a3b (2020-09-30T13:28:01+03:00, T-cdf44eb040316fff8c20f34069d5148e758f9ab7)
Running for foo...
./mdbx_load: at input line 1516: mdbx_cursor_put() error -30792, MDBX_MAP_FULL: Environment mapsize limit reached
```
no new entries loaded, stays at 2'500.

I  thought mdbx was able to extend the DB automatically. Else mdbx_load should propose an option to specify max size of the DB.

**Additional information**

By reducing the number of lines in the second batch, I'm able to load about 3'600 entries, 1MB of data.

**System**

 `Linux 5.6.0-2-amd64 #1 SMP Debian 5.6.14-2 (2020-06-09) x86_64 GNU/Linux`

**Comment by setop** [comment] 2020-11-15 03:10
here are the two input files

* [t1.txt](https://github.com/erthink/libmdbx/files/5541780/t1.txt)
* [t2.txt](https://github.com/erthink/libmdbx/files/5541781/t2.txt)

**Comment by erthink** [comment] 2020-11-15 04:34
Thank for reporting.

> `./mdbx_load: at input line 5000: mdbx_dbi_close() error -30780, MDBX_BAD_DBI: The specified DBI-handle is invalid or changed by another thread/transaction`

This is a bug.
In case data loaded into not a named sub-database (i.e. without `-s name` option), but into the "main" (unnamed) key-value space.
Will fixed soon.

> `./mdbx_load: at input line 1516: mdbx_cursor_put() error -30792, MDBX_MAP_FULL: Environment mapsize limit reached`
> 
> I thought mdbx was able to extend the DB automatically. Else mdbx_load should propose an option to specify max size of the DB.

Briefly: Please submit a PR if you need this feature.

More detailed:
 - `mdbx_load` is an auxiliary utility, mainly for transferring data from LMDB and BDB, as well as restoring from backups (that's why the bug you found went unnoticed).
 - your suggestion is reasonable, but still I will not implement it yet, as there are still a lot of cases when the functionality of these utilities is not enough.
 - please use following workaround or submit a PR with implementation based on the `mdbx_set_geometry()`, including man-page update.

Workaround:

1. Create a text file with the header using the following template
   ```
   VERSION=3
   geometry=l12288,c12288,u1073741824,s16777216,g8388608
   db_pagesize=4096
   HEADER=END
   DATA=END
   ```
   The order and purpose of numeric fields in the `geometry=` string matches the arguments of the `mdbx_set_geometry()` function, except for the last one (which sets the DB pagesize).
2. Create an new empty database `./mdbx_load pathname < header.txt` with the desired size, increment step, and shrink threshold.
3. Continue load you data in usual way (after I will commit a fix for the bug above).

**Closed** 2020-11-15 05:29 UTC

**Comment by setop** [comment] 2020-11-15 19:37
Thanks a lot for the reply.

I built from the last commit and indeed, no more MDBX_BAD_DBI error.

Unfortunately, the headers file does not fix MDBX_MAP_FULL.

I see `mdbx_env_set_geometry` proposes:

- intptr_t  	size_lower,
- intptr_t  	size_now,
- intptr_t  	size_upper,
- intptr_t  	growth_step,
- intptr_t  	shrink_threshold,
- intptr_t  	pagesize

I guess I grok the format of the headers:

- l	12288 ⇒ lower ? 12KB
- c	12288 ⇒ now ? 12KB
- u	1073741824 ⇒ upper ? 1GB, the interesting part to me
- s	16777216 ⇒ growth step ? 16MB
- g	8388608 ⇒ shrink ? 8M

But, with that, the db does not grow beyond 1MB.

**Comment by setop** [comment] 2020-11-15 19:46
Actually, there is something wierd:

When I do `./libmdbx/mdbx_load -T foo < header.txt` and then `./libmdbx/mdbx_dump -p foo`:

```
mdbx_dump v0.9.1-87-gd3b5d0c (2020-11-15T08:06:04+03:00, T-77f3e07db77441759eb439b1825bcb02816f4af0)
Running for foo...
VERSION=3
geometry=l12288,c65536,u1048576,s131072,g65536
mapsize=1048576
maxreaders=120
format=print
type=btree
db_pagesize=4096
duplicates=0
HEADER=END
 VERSION=3
 geometry=l12288,c12288,u1073741824,s16777216,g8388608
 db_pagesize=4096
 HEADER=END
DATA=END
```
It is like the header has been inserted as regual kv pairs.

**Comment by erthink** [comment] 2020-11-15 20:33
> Actually, there is something wierd:
> 
> When I do `./libmdbx/mdbx_load -T foo < header.txt` and then `./libmdbx/mdbx_dump -p foo`:
> 
> ```
> mdbx_dump v0.9.1-87-gd3b5d0c (2020-11-15T08:06:04+03:00, T-77f3e07db77441759eb439b1825bcb02816f4af0)
> Running for foo...
> VERSION=3
> geometry=l12288,c65536,u1048576,s131072,g65536
> mapsize=1048576
> maxreaders=120
> format=print
> type=btree
> db_pagesize=4096
> duplicates=0
> HEADER=END
>  VERSION=3
>  geometry=l12288,c12288,u1073741824,s16777216,g8388608
>  db_pagesize=4096
>  HEADER=END
> DATA=END
> ```
> 
> It is like the header has been inserted as regual kv pairs.

Please read my answer carefully.
Firstly, you should create the new DB by loading "header" without `-T` option.
Secondary, you should load your data into created DB with the `-T` option.

**Comment by setop** [comment] 2020-11-15 21:19
Sorry, I didn't read carefully.

After typing correctly, `./libmdbx/mdbx_dump -p foo` gives :

```
mdbx_dump v0.9.1-87-gd3b5d0c (2020-11-15T08:06:04+03:00, T-77f3e07db77441759eb439b1825bcb02816f4af0)
Running for foo...
VERSION=3
geometry=l12288,c1048576,u1048576,s131072,g65536
mapsize=1048576
maxreaders=120
format=print
type=btree
db_pagesize=4096
duplicates=0
HEADER=END
DATA=END
```
It seems the geometry parameter has not been taken into account. I still get MDBX_MAP_FULL when I try to load data.

**Comment by erthink** [comment] 2020-11-15 21:55
> It seems the geometry parameter has not been taken into account

Sorry, this was minor bug.
Fixed for now.

**Comment by setop** [comment] 2020-11-15 21:58
Reading from the code (mdbx_load.c#597), it seems `mapsize` if mandatory to load the geometry.

So I used as header:

```
VERSION=3
geometry=l12288,c12288,u1073741824,s16777216,g8388608
mapsize=1073741824
maxreaders=120
format=print
type=btree
db_pagesize=4096
duplicates=0
HEADER=END
DATA=END
```
And it works ! 2'263'514 entries, 520MB db, in 7 seconds :champagne: 
Thank for the workaround.
I'll continue playing :)

**Comment by setop** [comment] 2020-11-15 21:58
> > It seems the geometry parameter has not been taken into account
> 
> Sorry, this was minor bug.
> Fixed for now.

Cross posts.
Thanks you very much !

**Comment by gfanini** [comment] 2022-03-01 15:36
I am getting also MDBX_MAP_FULL inserting new keys when compiled mdbx 32 bit on windows, it doesn't do it compiling 64 bit,
I do this 

    rc = mdbx_env_create(&env);
    if (rc != MDBX_SUCCESS) {
        printf( "mdbx_env_create: (%d) %s\n", rc, mdbx_strerror(rc));
        goto bailout;
    }

    //mdbx_env_set_mapsize(env, 10485760);
    mdbx_env_set_geometry(env,
        0, // size_lower
        -1, // size_now
        INTPTR_MAX, // size_upper
        -1, // growth_step
        -1, // shrink_threshold
        -1); // pagesize


    rc = mdbx_env_open(env, "./example-db",
        MDBX_NOSUBDIR | MDBX_COALESCE | MDBX_LIFORECLAIM| /*MDBX_EXCLUSIVE |*/ MDBX_UTTERLY_NOSYNC | MDBX_WRITEMAP | MDBX_NOMETASYNC, 0664);

what am I doing wrong or should change ?

**Comment by erthink** [comment] 2022-03-01 18:22
The 32-bit Windows environment has significant limitations for the memory mapping size.
The actual limit depends on Windows version, the amount of memory, the size of the swap file, the current memory usage, etc.

Thus there are three reason for this:
 - It it possible that hardcoded some time ago limit is too high and should be reduced;
 - you system had to low available/free RAM;
 - some bug inside libmdbx during handling max- and/or default-values.
 
I'll check the last case tomorrow.
Thank for reporting.

**Comment by erthink** [comment] 2022-03-03 16:03
I checked your case on two Windows 10 machines.
In both cases, there is no `MDBX_MAP_FULL` problem, everything works as it should.
So, unconfirmed.

**Comment by gfanini** [comment] 2022-03-03 16:08
what are the settings for fastest insert rate like loading new records ?
it seems to be very slow doing one insert per transaction, what is the maximum number of puts per transaction ?
from the included test it seems to indicate "write transaction size" about 5 gb 64 bit and about 200 mb 32 bit, does that make sense to you that I don't know the code ?
is it possible to recover from map full by calling env sync ?

**Comment by erthink** [comment] 2022-03-03 16:28
> what am I doing wrong or should change ?

Seems none.
However, maybe you should have a 64-bit build for your data volume.

> what are the settings for fastest insert rate like loading new records ?

The `MDBX_UTTERLY_NOSYNC | MDBX_WRITEMAP` gives maximum performance, since at the same time writing to disk occurs implicitly only by the decision of the OS kernel.

> it seems to be very slow doing one insert per transaction, what is the maximum number of puts per transaction ?

Depending on the hardware performance in this mode, libmdbx provides from 20K to 10M insertions/updates per second.
What the performance do you observe and what do you expect?

With the `MDBX_WRITEMAP` there is no explicit limit on the transaction size.
On the other hand, the overhead to start and commit transaction is too low also.

So you can use 100-10K insertions per transaction.
But not too many, since during transaction any modified pages are always [CoW](https://en.wikipedia.org/wiki/Copy-on-write)ed, and thus large transaction require a large space of DB for inserted data and modified pages.

> is it possible to recover from map full by calling env sync ?

Yes.

**Comment by gfanini** [comment] 2022-03-03 17:36
with that environment setting  MDBX_UTTERLY_NOSYNC | MDBX_WRITEMAP

__cold intptr_t mdbx_limits_dbsize_max(intptr_t pagesize) {
  if (pagesize < 1)
    pagesize = (intptr_t)mdbx_default_pagesize();
  else if (unlikely(pagesize < (intptr_t)MIN_PAGESIZE ||
                    pagesize > (intptr_t)MAX_PAGESIZE ||
                    !is_powerof2((size_t)pagesize)))
    return -1;

  STATIC_ASSERT(MAX_MAPSIZE < INTPTR_MAX);
  const uint64_t limit = (1 + (uint64_t)MAX_PAGENO) * pagesize; MAX_PAGENO 2gb pagesize 65535
  return (limit < (intptr_t)MAX_MAPSIZE) ? (intptr_t)limit           
  
#define MAX_MAPSIZE32 UINT32_C(0x38000000) **decimal 939524096 about 900 mb ? it possible to increase to about 3 gb on 32 bit windows ?**
#else
#define MAX_MAPSIZE32 UINT32_C(0x7f000000) decimal 2130706432 about 2 gb 64 bit windows ?
#endif

                                         : (intptr_t)MAX_MAPSIZE;
}

so in case I cannot go with maximum insert speed setting above, is there a setting that allows > 1 gb db size on 32 bit windows

**Comment by erthink** [comment] 2022-03-03 17:58
> decimal 939524096 about 900 mb ? it possible to increase to about 3 gb on 32 bit windows ?

Yes, but it won't take off...

The hard limit is 2G address space for 32-bit Windows application.
For 32-bit kernel this 2G shared for all applications, and all shared libraries that are used, etc...

So if you have >256M data then 64-bit is recommended, but for >512M it is actually required.
Anyway, you can change this limit and try.

Moreover, you can fork libmdbx and use any reasonable value.
However, I don't see nor known any reason to accept such changes into upstream.

**Comment by gfanini** [comment] 2022-03-03 18:03
my situation is, unfortunately, I am stuck with legacy visual studio 2008, 32 bit because in that project there are tens of 32 bit dlls with all sort of 32 bit hard codings of pointers etc.

could this linker setting LARGEADDRESSAWARE for 3 gb help on windows 32 bit ?
https://docs.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses?view=msvc-170

**Comment by erthink** [comment] 2022-03-03 19:14
Yes, the `/LARGEADDRESSAWARE` should help you on a **64-bit Windows** host.
Using it should allow you add 1G to the `MAX_MAPSIZE32`.

**Comment by gfanini** [comment] 2022-03-03 20:14
ok, I changed it to 
#define MAX_MAPSIZE32 UINT32_C(0x70000000) // with /LARGEADDRESSAWARE on 64 bit windows o.s. (0x38000000)

and if I am not hallucinating it managed to insert 4 million 400 byte records, for 1.8 gb db, at a pace of 45k/s inserts with 1000 records per transaction, read is about 200k/s

Leonid, since I observe these real time db problems are quite delicate how to do efficient search and managing more data than can fit into memory all at once, for you information I am trying to replace a similar db called t-e-n-f-o-r-e have you ever heard of it because I think you are using the same techniquest, very similar performance to ldmbx ?

**Comment by erthink** [comment] 2022-03-03 20:45
For higher speeds, you should look towards in-memory databases, including preferring in-cluster replication instead of to-a-disk durability. For instance https://www.tarantool.io/

However, I think you shouldn't ask me "how does the universe work" ;)

**Comment by gfanini** [comment] 2022-03-03 22:09
I looked into mongo db not so much of my initiative but on a colleague's proposal but I subsequently discovered this type of real time performance is more similar to the underlying "wired tiger" storage subsystem
