### ISSUE TITLE
Failure on ppc64le architecture

### ISSUE THREAD

**Issue by Thermi** [erthink/libmdbx#157] opened 2021-01-27 12:54 UTC
Logs [here](https://gitlab.alpinelinux.org/Thermi/aports/-/jobs/305950)

log gz and test db are in the zip file.

[MR18221_ppc64le.zip](https://github.com/erthink/libmdbx/files/5880295/MR18221_ppc64le.zip)

**Comment by erthink** [comment] 2021-01-29 06:31
The cause of the problem was not a weak PowerPC memory model, but a trivial error that only occurred if the system memory page size was greater than 32K.
This is fixed for now in the `devel` branch.
Please check it.

However, later today there will be another fix for very large system page sizes.
Improvements I made to better support architectures with a weak memory model will also be merged, but after the fixes mentioned above.

Thank for reporting.

**Comment by Thermi** [comment] 2021-01-29 15:18
Seems to work now with the last patch (the one dealing with large page sizes).

**Closed** 2021-01-29 18:49 UTC
Labels: bug
